name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Allure commandline
        run: npm install -g allure-commandline

      - name: Run Playwright tests
        run: npx playwright test

      - name: Generate Allure report
        run: |
          allure generate ./allure-results --clean -o ./allure-report
          touch ./allure-report/.nojekyll
          cp index.html ./allure-report/
          # Fix relative paths in Allure report
          find ./allure-report -type f -name "*.html" -exec sed -i 's|href="/|href="./|g' {} \;
          find ./allure-report -type f -name "*.html" -exec sed -i 's|src="/|src="./|g' {} \;

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: https://vyacheslavde.github.io/PlaywrightMCP/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./docs/allure-report

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
